version: 0.2

phases:
  install:
    commands:
      - echo Entered the install phase...
      - echo Input Stack Name is $STACK_NAME
    finally:
      - echo This always runs even if the update or install command fails 
  pre_build:
    commands:
      - echo Entered the pre_build phase...
    finally:
      - echo This always runs even if the command fails 
  build:
    commands:
      - echo Entered the build phase...
      - echo Build started on `date`
      - aws s3 mb s3://automobile-ecommerce-lambda-source
      - aws s3 cp LambdaSourceZips s3://automobile-ecommerce-lambda-source --recursive
    finally:
      - echo This always runs even if the build command fails
  post_build:
    commands:
      - echo Entered the post_build phase...
      - echo Build completed on `date`

artifacts:
  files:
    - Infrastructure.yaml
  name: $STACK_NAME